import type {
  CaseRow,
  MonthlyData,
  TeamMember,
  DashboardSummary,
} from "@/types";

export const MOCK_CASES: CaseRow[] = [
  {
    id: 1001,
    name: "Smith, Jane",
    claim: "T2",
    level: "HEARING",
    status: "paid_in_full",
    expected: 9200,
    paid: 9200,
    office: "Jacksonville FL",
    assigned: "Drake",
    update: "PIF. All fees received.",
    sync: "synced",
    date: "2025-12-01",
  },
  {
    id: 1002,
    name: "Johnson, Robert",
    claim: "T2/T16",
    level: "HEARING",
    status: "partially_paid",
    expected: 6675,
    paid: 2050,
    office: "Miami FL",
    assigned: "Drake",
    update: "T16 received. Waiting on T2.",
    sync: "not_synced",
    date: "2025-10-20",
  },
  {
    id: 1003,
    name: "Garcia, Maria",
    claim: "T16",
    level: "INITIAL",
    status: "started",
    expected: 1810.41,
    paid: 0,
    office: "Tampa FL",
    assigned: "Drake",
    update: "Created Win Sheet.",
    sync: "not_synced",
    date: "2025-09-19",
  },
  {
    id: 1004,
    name: "Davis, William",
    claim: "T2",
    level: "HEARING",
    status: "closed",
    expected: 0,
    paid: 0,
    office: "Orlando FL",
    assigned: "Drake",
    update: "Unfavorable. No fee due.",
    sync: "not_synced",
    date: "2025-08-15",
  },
  {
    id: 1005,
    name: "Williams, Sarah",
    claim: "T2/T16",
    level: "RECON",
    status: "pending_payment",
    expected: 9600,
    paid: 0,
    office: "Ft. Lauderdale FL",
    assigned: "Drake",
    update: "Waiting on SSA payments.",
    sync: "not_synced",
    date: "2026-01-10",
  },
  {
    id: 1006,
    name: "Brown, Michael",
    claim: "T2",
    level: "HEARING",
    status: "paid_in_full",
    expected: 7000,
    paid: 7000,
    office: "Jacksonville FL",
    assigned: "Drake",
    update: "PIF. T2 fee received.",
    sync: "synced",
    date: "2025-11-10",
  },
  {
    id: 1007,
    name: "Martinez, Patricia",
    claim: "T2",
    level: "HEARING",
    status: "in_progress",
    expected: 3900,
    paid: 0,
    office: "Tallahassee FL",
    assigned: "Drake",
    update: "Awaiting award letter.",
    sync: "error",
    date: "2026-02-01",
  },
  {
    id: 1008,
    name: "Anderson, James",
    claim: "T2/T16",
    level: "HEARING",
    status: "partially_paid",
    expected: 11275,
    paid: 10250,
    office: "Miami FL",
    assigned: "Drake",
    update: "AUX fee still pending.",
    sync: "not_synced",
    date: "2025-09-28",
  },
];

export const MONTHLY_DATA: MonthlyData[] = [
  { month: "Sep", expected: 13085, collected: 0 },
  { month: "Oct", expected: 6675, collected: 2050 },
  { month: "Nov", expected: 7000, collected: 7000 },
  { month: "Dec", expected: 9200, collected: 9200 },
  { month: "Jan", expected: 9600, collected: 0 },
  { month: "Feb", expected: 3900, collected: 0 },
];

export const TEAM: TeamMember[] = [
  {
    name: "Drake",
    role: "Collections Specialist",
    cases: 8,
    collected: "$28,500",
  },
];

export const getMockSummary = (cases: CaseRow[]): DashboardSummary => {
  const expected = cases.reduce((s, c) => s + c.expected, 0);
  const paid = cases.reduce((s, c) => s + c.paid, 0);
  return {
    totalCases: cases.length,
    expected,
    paid,
    outstanding: expected - paid,
    pif: cases.filter((c) => c.status === "paid_in_full").length,
    syncErrors: cases.filter((c) => c.sync === "error").length,
    synced: cases.filter((c) => c.sync === "synced").length,
  };
};
